export const NEW_ATTENDANCE_REQUEST = "NEW_ATTENDANCE_REQUEST";
export const NEW_ATTENDANCE_SUCCESS = "NEW_ATTENDANCE_SUCCESS";
export const NEW_ATTENDANCE_FAIL = "NEW_ATTENDANCE_FAIL";

export const LOGIN_USER_ATTENDANCE_REQUEST = "LOGIN_USER_ATTENDANCE_REQUEST";
export const LOGIN_USER_ATTENDANCE_SUCCESS = "LOGIN_USER_ATTENDANCE_SUCCESS";
export const LOGIN_USER_ATTENDANCE_FAIL = "LOGIN_USER_ATTENDANCE_FAIL";

export const SPECIFIC_USER_ATTENDANCE_REQUEST = "SPECIFIC_USER_ATTENDANCE_REQUEST";
export const SPECIFIC_USER_ATTENDANCE_SUCCESS = "SPECIFIC_USER_ATTENDANCE_SUCCESS";
export const SPECIFIC_USER_ATTENDANCE_FAIL = "SPECIFIC_USER_ATTENDANCE_FAIL";

export const ALL_USER_ATTENDANCE_REQUEST = "ALL_USER_ATTENDANCE_REQUEST";
export const ALL_USER_ATTENDANCE_SUCCESS = "ALL_USER_ATTENDANCE_SUCCESS";
export const ALL_USER_ATTENDANCE_FAIL = "ALL_USER_ATTENDANCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
